### ISSUE TITLE
YouTube requests are being denied

### ISSUE THREAD

**Issue by TiberiumFusion** [samuelmaddock/gm-mediaplayer#29]
`[Request Error] The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.`

This happens when I try to request YouTube videos (circa 2020-01-19 right now). I've tried popular and unpopular videos, videos with ads and videos without ads. They all fail to play with the same error.

**Comment by WinterPhoenix96** [comment]
It’ll reset in about 30 minutes (every day at 12AM Pacific Time). This is indeed due to running into Quota Limits with the YouTube API.

Recently, YouTube adjusted the “cost” of certain requests, how many points they use, as well as the default limits for everything accessing the API.

This has lead to recent issues with both Cinema and Media Player running into the limit and unable to request any videos until it next resets.

**Comment by Mihoshika** [comment]
Having this same issue. Waited a day, and issue still persists.

**Comment by samuelmaddock** [comment]
#33
